server:
  port: 9090

spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

order-service:
  outbox-scheduler-fixed-rate: 10000
  outbox-scheduler-initial-delay: 10000

# swagger 설정
springdoc:
  swagger-ui:
    use-root-path: true
    path: /api
    operations-sorter: alpha
  api-docs:
    path: /api-docs